"""Init

Revision ID: 95889643a4be
Revises: 
Create Date: 2023-07-03 10:18:22.833164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95889643a4be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Calorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Calorie')
    # ### end Alembic commands ###
