"""add date

Revision ID: db51759692ee
Revises: 95889643a4be
Create Date: 2023-07-03 10:55:32.750004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db51759692ee'
down_revision = '95889643a4be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calorie', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Calorie', 'date')
    # ### end Alembic commands ###
